"""
DDL: создание таблиц и индексов.

Вызывается один раз при старте через Database.init_schema().
Не заменяет полноценные миграции — используй Alembic для продакшна.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.db.core import Database

USER_STATUSES = ("NEW", "TRIAL", "ACTIVE", "INACTIVE", "EXPIRED")


async def init_schema(db: "Database") -> None:
    status_list = ", ".join(f"'{s}'" for s in USER_STATUSES)

    create_users = f"""
        CREATE TABLE IF NOT EXISTS users (
            user_id               BIGINT PRIMARY KEY,
            username              TEXT,
            expire_at             TIMESTAMPTZ,
            vless_link            TEXT,
            uuid                  TEXT UNIQUE,
            status                TEXT NOT NULL DEFAULT 'NEW'
                                      CHECK (status IN ({status_list})),
            notified              BOOLEAN NOT NULL DEFAULT FALSE,
            balance               BIGINT  NOT NULL DEFAULT 0 CHECK (balance >= 0),
            last_billing_date     DATE,
            low_balance_notified  BOOLEAN NOT NULL DEFAULT FALSE
        );
    """

    create_devices = """
        CREATE TABLE IF NOT EXISTS devices (
            id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id        BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            device_name    TEXT    NOT NULL,
            client_uuid    TEXT    NOT NULL UNIQUE,
            vless_link     TEXT,
            monthly_cost   INTEGER NOT NULL DEFAULT 10000 CHECK (monthly_cost >= 0),
            created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            is_active      BOOLEAN NOT NULL DEFAULT TRUE,
            disabled_at    TIMESTAMPTZ,
            disabled_reason TEXT
        );
    """

    create_payments = """
        CREATE TABLE IF NOT EXISTS payments (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id             BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            payload             TEXT    NOT NULL,
            telegram_charge_id  TEXT    NOT NULL,
            provider_charge_id  TEXT    NOT NULL,
            amount              INTEGER NOT NULL CHECK (amount >= 0),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            status              TEXT    NOT NULL DEFAULT 'PENDING',
            idempotency_key     TEXT
        );
    """

    create_support_tickets = """
        CREATE TABLE IF NOT EXISTS support_tickets (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id     BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            message     TEXT    NOT NULL
                            CHECK (char_length(message) >= 5 AND char_length(message) <= 1000),
            status      TEXT    NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'answered', 'closed')),
            files       JSONB   NOT NULL DEFAULT '[]'::jsonb,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            answered_at TIMESTAMPTZ
        );
    """

    create_balance_transactions = """
        CREATE TABLE IF NOT EXISTS balance_transactions (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id          BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            kind             TEXT    NOT NULL
                                 CHECK (kind IN (
                                     'TOPUP',
                                     'DAILY_CHARGE',
                                     'CHARGE',
                                     'ADMIN_ADJUSTMENT',
                                     'REFUND',
                                     'BONUS'
                                 )),
            amount_cents     BIGINT  NOT NULL CHECK (amount_cents >= 0),
            balance_before   BIGINT  NOT NULL CHECK (balance_before >= 0),
            balance_after    BIGINT  NOT NULL CHECK (balance_after >= 0),
            reference_type   TEXT,
            reference_id     TEXT,
            idempotency_key  TEXT,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
    """

    # --- ALTER: добавляем колонки если ещё нет (для уже существующих БД) ---
    alter_devices = """
        ALTER TABLE devices
            ADD COLUMN IF NOT EXISTS is_active       BOOLEAN NOT NULL DEFAULT TRUE,
            ADD COLUMN IF NOT EXISTS disabled_at     TIMESTAMPTZ,
            ADD COLUMN IF NOT EXISTS disabled_reason TEXT;
    """

    alter_payments = """
        ALTER TABLE payments
            ADD COLUMN IF NOT EXISTS status          TEXT NOT NULL DEFAULT 'PENDING',
            ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
    """

    alter_users_notifications = """
        ALTER TABLE users
            ADD COLUMN IF NOT EXISTS low_balance_notified BOOLEAN NOT NULL DEFAULT FALSE;
    """

    alter_balance_transactions_kind = """
        ALTER TABLE balance_transactions
            DROP CONSTRAINT IF EXISTS balance_transactions_kind_check;
        ALTER TABLE balance_transactions
            ADD CONSTRAINT balance_transactions_kind_check
            CHECK (kind IN (
                'TOPUP',
                'DAILY_CHARGE',
                'CHARGE',
                'ADMIN_ADJUSTMENT',
                'REFUND',
                'BONUS'
            ));
    """

    # --- Индексы ---
    indexes = """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_tg_charge_id
            ON payments(telegram_charge_id);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_provider_charge_id
            ON payments(provider_charge_id);
        CREATE INDEX IF NOT EXISTS idx_payments_user_id
            ON payments(user_id);
        CREATE INDEX IF NOT EXISTS idx_devices_user_id
            ON devices(user_id);
        CREATE INDEX IF NOT EXISTS idx_devices_user_id_is_active
            ON devices(user_id, is_active);
        CREATE INDEX IF NOT EXISTS idx_users_uuid
            ON users(uuid);
        CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id
            ON support_tickets(user_id);
        CREATE INDEX IF NOT EXISTS idx_support_tickets_user_created
            ON support_tickets(user_id, created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_balance_transactions_user_id
            ON balance_transactions(user_id);
        CREATE INDEX IF NOT EXISTS idx_balance_transactions_user_created_at
            ON balance_transactions(user_id, created_at DESC);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_balance_transactions_idempotency_key
            ON balance_transactions(idempotency_key)
            WHERE idempotency_key IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_idempotency_key
            ON payments(idempotency_key)
            WHERE idempotency_key IS NOT NULL;
    """

    async with db.transaction() as conn:
        await conn.execute(create_users)
        await conn.execute(create_devices)
        await conn.execute(create_payments)
        await conn.execute(create_support_tickets)
        await conn.execute(create_balance_transactions)
        # ALTER-ы идут после CREATE чтобы не падать на старых БД
        await conn.execute(alter_devices)
        await conn.execute(alter_payments)
        await conn.execute(alter_users_notifications)
        await conn.execute(alter_balance_transactions_kind)
        await conn.execute(indexes)
