"""
Асинхронный слой доступа к PostgreSQL для Metron VPN-бота.

Модель:
- 1 user -> many devices
- paid-доступ живёт через balance и daily billing
- trial использует expire_at
- платежи идемпотентны
- деньги храним как int (копейки), наружу отдаём Decimal
"""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager
from datetime import date, datetime
from decimal import Decimal
from typing import Any, AsyncIterator, Dict, List, Optional

import asyncpg

logger = logging.getLogger(__name__)

USER_STATUSES = ("NEW", "TRIAL", "ACTIVE", "INACTIVE", "EXPIRED")


class Database:
    """Асинхронный доступ к PostgreSQL."""

    def __init__(self, dsn: str, min_size: int = 2, max_size: int = 10):
        self._dsn = dsn
        self._pool: Optional[asyncpg.Pool] = None
        self._min_size = min_size
        self._max_size = max_size

    async def connect(self) -> None:
        self._pool = await asyncpg.create_pool(
            dsn=self._dsn,
            min_size=self._min_size,
            max_size=self._max_size,
            command_timeout=10.0,
        )
        logger.info("DB pool created (min=%s, max=%s)", self._min_size, self._max_size)

    async def disconnect(self) -> None:
        if self._pool:
            await self._pool.close()
            logger.info("DB pool closed")

    @asynccontextmanager
    async def connection(self) -> AsyncIterator[asyncpg.Connection]:
        if not self._pool:
            raise RuntimeError("Pool not initialized")
        async with self._pool.acquire() as conn:
            yield conn

    @asynccontextmanager
    async def transaction(self) -> AsyncIterator[asyncpg.Connection]:
        if not self._pool:
            raise RuntimeError("Pool not initialized")
        async with self._pool.acquire() as conn:
            async with conn.transaction():
                yield conn

    async def init_schema(self) -> None:
        status_list = ", ".join(f"'{s}'" for s in USER_STATUSES)

        create_users = f"""
            CREATE TABLE IF NOT EXISTS users (
                user_id BIGINT PRIMARY KEY,
                username TEXT,
                expire_at TIMESTAMPTZ,
                vless_link TEXT,
                uuid TEXT UNIQUE,
                status TEXT NOT NULL DEFAULT 'NEW'
                    CHECK (status IN ({status_list})),
                notified BOOLEAN NOT NULL DEFAULT FALSE,
                balance BIGINT NOT NULL DEFAULT 0 CHECK (balance >= 0),
                last_billing_date DATE
            );
        """

        create_devices = """
            CREATE TABLE IF NOT EXISTS devices (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                device_name TEXT NOT NULL,
                client_uuid TEXT NOT NULL UNIQUE,
                vless_link TEXT,
                monthly_cost INTEGER NOT NULL DEFAULT 10000 CHECK (monthly_cost >= 0),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """

        create_payments = """
            CREATE TABLE IF NOT EXISTS payments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                payload TEXT NOT NULL,
                telegram_charge_id TEXT NOT NULL,
                provider_charge_id TEXT NOT NULL,
                amount INTEGER NOT NULL CHECK (amount >= 0),
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """

        create_indexes = """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_tg_charge_id
                ON payments(telegram_charge_id);
            CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_provider_charge_id
                ON payments(provider_charge_id);
            CREATE INDEX IF NOT EXISTS idx_payments_user_id ON payments(user_id);
            CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);
            CREATE INDEX IF NOT EXISTS idx_users_uuid ON users(uuid);
        """

        create_active_device_indexes = """
            CREATE INDEX IF NOT EXISTS idx_devices_user_id_is_active
                ON devices(user_id, is_active);
        """

        alter_devices = """
            ALTER TABLE devices
                ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
                ADD COLUMN IF NOT EXISTS disabled_at TIMESTAMPTZ,
                ADD COLUMN IF NOT EXISTS disabled_reason TEXT;
        """

        alter_payments = """
            ALTER TABLE payments
                ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'PENDING',
                ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
        """

        alter_users_notifications = """
        ALTER TABLE users
            ADD COLUMN IF NOT EXISTS low_balance_notified BOOLEAN NOT NULL DEFAULT FALSE;
        """

        create_balance_transactions = """
            CREATE TABLE IF NOT EXISTS balance_transactions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                kind TEXT NOT NULL
                    CHECK (kind IN (
                        'TOPUP',
                        'DAILY_CHARGE',
                        'ADMIN_ADJUSTMENT',
                        'REFUND',
                        'BONUS'
                    )),
                amount_cents BIGINT NOT NULL CHECK (amount_cents >= 0),
                balance_before BIGINT NOT NULL CHECK (balance_before >= 0),
                balance_after BIGINT NOT NULL CHECK (balance_after >= 0),
                reference_type TEXT,
                reference_id TEXT,
                idempotency_key TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );
        """

        create_balance_indexes = """
            CREATE INDEX IF NOT EXISTS idx_balance_transactions_user_id
                ON balance_transactions(user_id);

            CREATE INDEX IF NOT EXISTS idx_balance_transactions_user_created_at
                ON balance_transactions(user_id, created_at DESC);

            CREATE UNIQUE INDEX IF NOT EXISTS idx_balance_transactions_idempotency_key
                ON balance_transactions(idempotency_key)
                WHERE idempotency_key IS NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_idempotency_key
                ON payments(idempotency_key)
                WHERE idempotency_key IS NOT NULL;
        """

        async with self.transaction() as conn:
            await conn.execute(create_users)
            await conn.execute(create_devices)
            await conn.execute(create_payments)
            await conn.execute(alter_devices)           # ← сначала добавляем колонки
            await conn.execute(alter_payments)
            await conn.execute(alter_users_notifications)
            await conn.execute(create_balance_transactions)
            await conn.execute(create_indexes)          # ← потом индексы
            await conn.execute(create_active_device_indexes)  # ← теперь is_active уже есть
            await conn.execute(create_balance_indexes)      

    @staticmethod
    def _cents_to_rubles(cents: int) -> Decimal:
        return Decimal(cents) / 100

    async def set_user_balance(self, user_id: int, amount_cents: int) -> bool:
        if amount_cents < 0:
            raise ValueError("amount_cents must be >= 0")

        async with self.transaction() as conn:
            row = await conn.fetchrow(
                "SELECT balance FROM users WHERE user_id = $1 FOR UPDATE",
                user_id,
            )
            if not row:
                return False

            balance_before = row["balance"]
            balance_after = amount_cents

            await conn.execute(
                "UPDATE users SET balance = $1 WHERE user_id = $2",
                balance_after,
                user_id,
            )

            await self._create_balance_transaction(
                conn=conn,
                user_id=user_id,
                kind="ADMIN_ADJUSTMENT",
                amount_cents=abs(balance_after - balance_before),
                balance_before=balance_before,
                balance_after=balance_after,
                reference_type="admin_set_balance",
                reference_id=None,
                idempotency_key=None,
            )

            return True


    async def add_balance_atomic(
        self,
        user_id: int,
        amount_cents: int,
        reference_type: Optional[str] = "payment",
        reference_id: Optional[str] = None,
        idempotency_key: Optional[str] = None,
    ) -> Optional[Decimal]:
        if amount_cents < 0:
            raise ValueError("amount_cents must be >= 0")

        async with self.transaction() as conn:
            row = await conn.fetchrow(
                "SELECT balance FROM users WHERE user_id = $1 FOR UPDATE",
                user_id,
            )
            if not row:
                return None

            balance_before = row["balance"]

            updated = await conn.fetchrow(
                """
                UPDATE users
                SET balance = balance + $1
                WHERE user_id = $2
                RETURNING balance
                """,
                amount_cents,
                user_id,
            )
            balance_after = updated["balance"]

            await self._create_balance_transaction(
                conn=conn,
                user_id=user_id,
                kind="TOPUP",
                amount_cents=amount_cents,
                balance_before=balance_before,
                balance_after=balance_after,
                reference_type=reference_type,
                reference_id=reference_id,
                idempotency_key=idempotency_key,
            )

            return self._cents_to_rubles(balance_after)

    async def _create_balance_transaction(
        self,
        conn: asyncpg.Connection,
        user_id: int,
        kind: str,
        amount_cents: int,
        balance_before: int,
        balance_after: int,
        reference_type: Optional[str] = None,
        reference_id: Optional[str] = None,
        idempotency_key: Optional[str] = None,
    ) -> int:
        row = await conn.fetchrow(
            """
            INSERT INTO balance_transactions (
                user_id,
                kind,
                amount_cents,
                balance_before,
                balance_after,
                reference_type,
                reference_id,
                idempotency_key
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
            RETURNING id
            """,
            user_id,
            kind,
            amount_cents,
            balance_before,
            balance_after,
            reference_type,
            reference_id,
            idempotency_key,
        )
        return row["id"]

    async def charge_balance_atomic(
        self,
        user_id: int,
        amount_cents: int,
        reference_type: Optional[str] = "manual_charge",
        reference_id: Optional[str] = None,
        idempotency_key: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        if amount_cents < 0:
            raise ValueError("amount_cents must be >= 0")

        async with self.transaction() as conn:
            row = await conn.fetchrow(
                "SELECT balance FROM users WHERE user_id = $1 FOR UPDATE",
                user_id,
            )
            if not row:
                return None

            balance_before = row["balance"]
            if balance_before < amount_cents:
                return {
                    "charged": False,
                    "insufficient_funds": True,
                    "balance_before": self._cents_to_rubles(balance_before),
                    "balance_after": self._cents_to_rubles(balance_before),
                }

            updated = await conn.fetchrow(
                """
                UPDATE users
                SET balance = balance - $1
                WHERE user_id = $2 AND balance >= $1
                RETURNING balance
                """,
                amount_cents,
                user_id,
            )
            if not updated:
                return {
                    "charged": False,
                    "insufficient_funds": True,
                    "balance_before": self._cents_to_rubles(balance_before),
                    "balance_after": self._cents_to_rubles(balance_before),
                }

            balance_after = updated["balance"]

            await self._create_balance_transaction(
                conn=conn,
                user_id=user_id,
                kind="ADMIN_ADJUSTMENT",
                amount_cents=amount_cents,
                balance_before=balance_before,
                balance_after=balance_after,
                reference_type=reference_type,
                reference_id=reference_id,
                idempotency_key=idempotency_key,
            )

            return {
                "charged": True,
                "insufficient_funds": False,
                "balance_before": self._cents_to_rubles(balance_before),
                "balance_after": self._cents_to_rubles(balance_after),
            }

    async def charge_daily_billing_atomic(
        self,
        user_id: int,
        amount_cents: int,
        billing_date: date,
    ) -> Optional[Dict[str, Any]]:
        if amount_cents < 0:
            raise ValueError("amount_cents must be >= 0")

        async with self.transaction() as conn:
            row = await conn.fetchrow(
                "SELECT balance, last_billing_date FROM users WHERE user_id = $1 FOR UPDATE",
                user_id,
            )
            if not row:
                return None

            balance_before = row["balance"]
            last_bill = row["last_billing_date"]

            if last_bill is not None and last_bill == billing_date:
                return {
                    "charged": False,
                    "already_charged_today": True,
                    "insufficient_funds": False,
                    "balance_before": self._cents_to_rubles(balance_before),
                    "balance_after": self._cents_to_rubles(balance_before),
                }

            if balance_before < amount_cents:
                return {
                    "charged": False,
                    "already_charged_today": False,
                    "insufficient_funds": True,
                    "balance_before": self._cents_to_rubles(balance_before),
                    "balance_after": self._cents_to_rubles(balance_before),
                }

            updated = await conn.fetchrow(
                """
                UPDATE users
                SET balance = balance - $1, last_billing_date = $2
                WHERE user_id = $3 AND balance >= $1
                RETURNING balance
                """,
                amount_cents,
                billing_date,
                user_id,
            )
            if not updated:
                return {
                    "charged": False,
                    "already_charged_today": False,
                    "insufficient_funds": True,
                    "balance_before": self._cents_to_rubles(balance_before),
                    "balance_after": self._cents_to_rubles(balance_before),
                }

            balance_after = updated["balance"]

            await self._create_balance_transaction(
                conn=conn,
                user_id=user_id,
                kind="DAILY_CHARGE",
                amount_cents=amount_cents,
                balance_before=balance_before,
                balance_after=balance_after,
                reference_type="billing",
                reference_id=str(billing_date),
                idempotency_key=f"daily:{user_id}:{billing_date.isoformat()}",
            )

            return {
                "charged": True,
                "already_charged_today": False,
                "insufficient_funds": False,
                "balance_before": self._cents_to_rubles(balance_before),
                "balance_after": self._cents_to_rubles(balance_after),
            }

    async def save_user(
        self,
        user_id: int,
        username: str,
        expire_at: Optional[datetime],
        vless_link: Optional[str],
        uuid_val: Optional[str],
        status: str = "TRIAL",
    ) -> None:
        async with self.transaction() as conn:
            await conn.execute(
                """
                INSERT INTO users (
                    user_id, username, expire_at, vless_link, uuid, status, notified, low_balance_notified
                )
                VALUES ($1, $2, $3, $4, $5, $6, FALSE, FALSE)
                ON CONFLICT (user_id) DO UPDATE SET
                    username = EXCLUDED.username,
                    expire_at = EXCLUDED.expire_at,
                    vless_link = EXCLUDED.vless_link,
                    uuid = EXCLUDED.uuid,
                    status = EXCLUDED.status,
                    notified = FALSE,
                    low_balance_notified = FALSE
                """,
                user_id, username, expire_at, vless_link, uuid_val, status,
            )

    async def get_user_data_dict(self, user_id: int) -> Optional[Dict[str, Any]]:
        async with self.connection() as conn:
            row = await conn.fetchrow(
                """
                SELECT
                    expire_at,
                    vless_link,
                    uuid,
                    username,
                    status,
                    balance,
                    notified,
                    low_balance_notified
                FROM users
                WHERE user_id = $1
                """,
                user_id,
            )
            return dict(row) if row else None

    async def get_user_balance(self, user_id: int) -> Optional[Decimal]:
        async with self.connection() as conn:
            row = await conn.fetchrow(
                "SELECT balance FROM users WHERE user_id = $1",
                user_id,
            )
            return self._cents_to_rubles(row["balance"]) if row else None

    async def get_user_by_uuid(self, uuid_val: str) -> Optional[Dict[str, Any]]:
        async with self.connection() as conn:
            row = await conn.fetchrow(
                """
                 SELECT user_id, username, expire_at, vless_link, uuid,
                       status, notified, low_balance_notified, balance, last_billing_date
                FROM users
                WHERE uuid = $1
                """,
                uuid_val,
            )
            return dict(row) if row else None

    async def update_user_link(
        self,
        user_id: int,
        new_link: str,
        uuid_val: Optional[str] = None,
    ) -> None:
        async with self.transaction() as conn:
            if uuid_val:
                await conn.execute(
                    "UPDATE users SET vless_link = $1, uuid = $2 WHERE user_id = $3",
                    new_link,
                    uuid_val,
                    user_id,
                )
            else:
                await conn.execute(
                    "UPDATE users SET vless_link = $1 WHERE user_id = $2",
                    new_link,
                    user_id,
                )

    async def deactivate_panel_client(self, client_uuid: str) -> bool:
        async with self.transaction() as conn:
            result = await conn.execute(
                "UPDATE users SET status = 'INACTIVE' WHERE uuid = $1",
                client_uuid,
            )
            return result != "UPDATE 0"

    async def update_user_last_billing_date(self, user_id: int, billing_date: date) -> None:
        async with self.transaction() as conn:
            await conn.execute(
                "UPDATE users SET last_billing_date = $1 WHERE user_id = $2",
                billing_date,
                user_id,
            )

    async def get_user_last_billing_date(self, user_id: int) -> Optional[date]:
        async with self.connection() as conn:
            row = await conn.fetchrow(
                "SELECT last_billing_date FROM users WHERE user_id = $1",
                user_id,
            )
            return row["last_billing_date"] if row else None

    async def ensure_user_stub(self, user_id: int, username: str) -> None:
        async with self.transaction() as conn:
            await conn.execute(
                """
                INSERT INTO users (user_id, username, status, notified, balance)
                VALUES ($1, $2, 'NEW', FALSE, 0)
                ON CONFLICT (user_id) DO UPDATE SET
                    username = COALESCE(users.username, EXCLUDED.username)
                """,
                user_id,
                username,
            )

    async def save_paid_access(
        self,
        user_id: int,
        username: str,
        vless_link: str,
        uuid_val: str,
    ) -> None:
        async with self.transaction() as conn:
            await conn.execute(
                """
                INSERT INTO users (
                    user_id, username, vless_link, uuid, status, notified, low_balance_notified
                )
                VALUES ($1, $2, $3, $4, 'ACTIVE', FALSE, FALSE)
                ON CONFLICT (user_id) DO UPDATE SET
                    username = EXCLUDED.username,
                    vless_link = EXCLUDED.vless_link,
                    uuid = EXCLUDED.uuid,
                    status = 'ACTIVE',
                    notified = FALSE,
                    low_balance_notified = FALSE
                """,
                user_id, username, vless_link, uuid_val,
            )

    async def add_device(
        self,
        user_id: int,
        device_name: str,
        client_uuid: str,
        vless_link: str,
        monthly_cost_cents: int = 10000,
    ) -> int:
        """
        Добавить устройство, вернуть его id.

        Если user_id не существует, сработает ограничение внешнего ключа
        и asyncpg выбросит ForeignKeyViolationError — это нормально,
        его ловим и логируем на уровне обработчика бота.
        """
        async with self.transaction() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO devices (user_id, device_name, client_uuid, vless_link, monthly_cost)
                VALUES ($1, $2, $3, $4, $5)
                RETURNING id
                """,
                user_id,
                device_name,
                client_uuid,
                vless_link,
                monthly_cost_cents,
            )
            return row["id"]

    async def remove_device(self, device_id: int, user_id: Optional[int] = None) -> int:
        async with self.transaction() as conn:
            if user_id:
                result = await conn.execute(
                    "DELETE FROM devices WHERE id = $1 AND user_id = $2",
                    device_id,
                    user_id,
                )
            else:
                result = await conn.execute(
                    "DELETE FROM devices WHERE id = $1",
                    device_id,
                )
            return int(result.split()[-1])
            
    async def deactivate_device(
        self,
        device_id: int,
        user_id: Optional[int] = None,
        reason: Optional[str] = None,
    ) -> bool:
        async with self.transaction() as conn:
            if user_id is not None:
                result = await conn.execute(
                    """
                    UPDATE devices
                    SET is_active = FALSE,
                        disabled_at = NOW(),
                        disabled_reason = $1
                    WHERE id = $2 AND user_id = $3
                    """,
                    reason,
                    device_id,
                    user_id,
                )
            else:
                result = await conn.execute(
                    """
                    UPDATE devices
                    SET is_active = FALSE,
                        disabled_at = NOW(),
                        disabled_reason = $1
                    WHERE id = $2
                    """,
                    reason,
                    device_id,
                )
            return result != "UPDATE 0"

    async def activate_device(
        self,
        device_id: int,
        user_id: Optional[int] = None,
    ) -> bool:
        async with self.transaction() as conn:
            if user_id is not None:
                result = await conn.execute(
                    """
                    UPDATE devices
                    SET is_active = TRUE,
                        disabled_at = NULL,
                        disabled_reason = NULL
                    WHERE id = $1 AND user_id = $2
                    """,
                    device_id,
                    user_id,
                )
            else:
                result = await conn.execute(
                    """
                    UPDATE devices
                    SET is_active = TRUE,
                        disabled_at = NULL,
                        disabled_reason = NULL
                    WHERE id = $1
                    """,
                    device_id,
                )
            return result != "UPDATE 0"

    async def get_balance_transactions(
        self,
        user_id: int,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        async with self.connection() as conn:
            rows = await conn.fetch(
                """
                SELECT
                    id,
                    user_id,
                    kind,
                    amount_cents,
                    balance_before,
                    balance_after,
                    reference_type,
                    reference_id,
                    idempotency_key,
                    created_at
                FROM balance_transactions
                WHERE user_id = $1
                ORDER BY created_at DESC, id DESC
                LIMIT $2
                """,
                user_id,
                limit,
            )

            return [
                {
                    **dict(r),
                    "amount": self._cents_to_rubles(r["amount_cents"]),
                    "balance_before_rub": self._cents_to_rubles(r["balance_before"]),
                    "balance_after_rub": self._cents_to_rubles(r["balance_after"]),
                }
                for r in rows
            ]

    async def get_user_devices(self, user_id: int) -> List[Dict[str, Any]]:
        async with self.connection() as conn:
            rows = await conn.fetch(
                """
                SELECT
                    id,
                    device_name,
                    client_uuid,
                    vless_link,
                    monthly_cost,
                    created_at,
                    is_active,
                    disabled_at,
                    disabled_reason
                FROM devices
                WHERE user_id = $1
                ORDER BY created_at DESC
                """,
                user_id,
            )
            return [
                {**dict(r), "monthly_cost": self._cents_to_rubles(r["monthly_cost"])}
                for r in rows
            ]

    async def get_device_by_id(self, device_id: int) -> Optional[Dict[str, Any]]:
        async with self.connection() as conn:
            row = await conn.fetchrow(
                """
                SELECT
                    id,
                    user_id,
                    device_name,
                    client_uuid,
                    vless_link,
                    monthly_cost,
                    created_at,
                    is_active,
                    disabled_at,
                    disabled_reason
                FROM devices
                WHERE id = $1
                """,
                device_id,
            )
            if not row:
                return None
            return {**dict(row), "monthly_cost": self._cents_to_rubles(row["monthly_cost"])}

    async def get_all_users_with_devices(self) -> List[int]:
        async with self.connection() as conn:
            rows = await conn.fetch(
                """
                SELECT DISTINCT d.user_id
                FROM devices d
                JOIN users u ON u.user_id = d.user_id
                WHERE u.status = 'ACTIVE'
                AND d.is_active = TRUE
                ORDER BY d.user_id
                """
            )
            return [r["user_id"] for r in rows]

    # ФИКС
    async def get_user_total_monthly_cost(self, user_id: int) -> Decimal:
        async with self.connection() as conn:
            row = await conn.fetchrow(
                """
                SELECT COALESCE(SUM(monthly_cost), 0) AS total
                FROM devices
                WHERE user_id = $1
                AND is_active = TRUE
                """,
                user_id,
            )
            return self._cents_to_rubles(row["total"])

    async def get_payment_by_charge_ids(
        self,
        telegram_charge_id: str,
        provider_charge_id: str,
    ) -> Optional[Dict[str, Any]]:
        async with self.connection() as conn:
            row = await conn.fetchrow(
                """
                SELECT id, user_id, payload, telegram_charge_id, provider_charge_id,
                       amount, created_at
                FROM payments
                WHERE telegram_charge_id = $1 OR provider_charge_id = $2
                """,
                telegram_charge_id,
                provider_charge_id,
            )
            return dict(row) if row else None

    async def set_low_balance_notified(self, user_id: int, value: bool) -> None:
        async with self.transaction() as conn:
            await conn.execute(
                "UPDATE users SET low_balance_notified = $1 WHERE user_id = $2",
                value,
                user_id,
            )

    async def record_payment_idempotent(
        self,
        user_id: int,
        payload: str,
        telegram_charge_id: str,
        provider_charge_id: str,
        amount_cents: int,
    ) -> Dict[str, Any]:
        """
        Идемпотентная запись платежа.

        Стратегия:
        1) Пытаемся вставить платеж.
           - Если вставился → новый платеж.
           - Если сработал любой уникальный конфликт (любой индекс) → вставки нет.
        2) В случае конфликта один раз читаем существующую запись
           по telegram_charge_id / provider_charge_id и возвращаем её.
        """
        if amount_cents < 0:
            raise ValueError("amount_cents must be >= 0")

        async with self.transaction() as conn:
            inserted = await conn.fetchrow(
                """
                INSERT INTO payments (
                    user_id,
                    payload,
                    telegram_charge_id,
                    provider_charge_id,
                    amount
                )
                VALUES ($1, $2, $3, $4, $5)
                ON CONFLICT DO NOTHING
                RETURNING
                    id,
                    user_id,
                    payload,
                    telegram_charge_id,
                    provider_charge_id,
                    amount,
                    created_at
                """,
                user_id,
                payload,
                telegram_charge_id,
                provider_charge_id,
                amount_cents,
            )
            if inserted:
                return {"created": True, "payment": dict(inserted)}

            existing = await conn.fetchrow(
                """
                SELECT
                    id,
                    user_id,
                    payload,
                    telegram_charge_id,
                    provider_charge_id,
                    amount,
                    created_at
                FROM payments
                WHERE telegram_charge_id = $1
                   OR provider_charge_id = $2
                """,
                telegram_charge_id,
                provider_charge_id,
            )
            if existing:
                return {"created": False, "payment": dict(existing)}

            raise RuntimeError(
                "Payment idempotency invariant violated: "
                f"telegram_charge_id={telegram_charge_id}, "
                f"provider_charge_id={provider_charge_id}"
            )

    async def get_expired_trial_users(self) -> List[int]:
        """Возвращает user_id всех пользователей с истёкшим триалом."""
        async with self.connection() as conn:
            rows = await conn.fetch(
                """
                SELECT user_id
                FROM users
                WHERE status = 'TRIAL'
                  AND expire_at IS NOT NULL
                  AND expire_at < NOW()
                """
            )
            return [r["user_id"] for r in rows]

    async def update_user_status(self, user_id: int, status: str) -> bool:
        """Точечно обновляет статус пользователя без сброса других полей."""
        if status not in USER_STATUSES:
            raise ValueError(f"Invalid status: {status}. Must be one of {USER_STATUSES}")
        async with self.transaction() as conn:
            result = await conn.execute(
                "UPDATE users SET status = $1 WHERE user_id = $2",
                status,
                user_id,
            )
            return result != "UPDATE 0"


_db: Optional[Database] = None

async def init_db() -> Database:
    global _db
    if _db is not None:
        return _db

    dsn = os.environ["DATABASE_URL"]
    db = Database(dsn)
    await db.connect()
    await db.init_schema()
    _db = db
    return db

async def close_db() -> None:
    global _db
    if _db is not None:
        await _db.disconnect()
        _db = None

def get_db() -> Database:
    if _db is None:
        raise RuntimeError("Database is not initialized. Call init_db() first.")
    return _db

async def add_balance_atomic(
    user_id: int,
    amount_cents: int,
    reference_type: Optional[str] = "payment",
    reference_id: Optional[str] = None,
    idempotency_key: Optional[str] = None,
) -> Optional[Decimal]:
    return await get_db().add_balance_atomic(
        user_id=user_id,
        amount_cents=amount_cents,
        reference_type=reference_type,
        reference_id=reference_id,
        idempotency_key=idempotency_key,
    )

async def charge_balance_atomic(
    user_id: int,
    amount_cents: int,
    reference_type: Optional[str] = "manual_charge",
    reference_id: Optional[str] = None,
    idempotency_key: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    return await get_db().charge_balance_atomic(
        user_id=user_id,
        amount_cents=amount_cents,
        reference_type=reference_type,
        reference_id=reference_id,
        idempotency_key=idempotency_key,
    )

async def charge_daily_billing_atomic(
    user_id: int,
    amount_cents: int,
    billing_date: date,
) -> Optional[Dict[str, Any]]:
    return await get_db().charge_daily_billing_atomic(
        user_id=user_id,
        amount_cents=amount_cents,
        billing_date=billing_date,
    )


async def save_user(
    user_id: int,
    username: str,
    expire_at: Optional[datetime],
    vless_link: Optional[str],
    uuid_val: Optional[str],
    status: str = "TRIAL",
) -> None:
    await get_db().save_user(
        user_id=user_id,
        username=username,
        expire_at=expire_at,
        vless_link=vless_link,
        uuid_val=uuid_val,
        status=status,
    )

async def update_user_link(
    user_id: int,
    new_link: str,
    uuid_val: Optional[str] = None,
) -> None:
    await get_db().update_user_link(user_id, new_link, uuid_val)


async def deactivate_panel_client(client_uuid: str) -> bool:
    return await get_db().deactivate_panel_client(client_uuid)

async def update_user_last_billing_date(user_id: int, billing_date: date) -> None:
    await get_db().update_user_last_billing_date(user_id, billing_date)

async def get_user_last_billing_date(user_id: int) -> Optional[date]:
    return await get_db().get_user_last_billing_date(user_id)

async def remove_device(device_id: int, user_id: Optional[int] = None) -> int:
    return await get_db().remove_device(device_id, user_id)

async def get_user_data_dict(user_id: int) -> Optional[Dict[str, Any]]:
    return await get_db().get_user_data_dict(user_id)

async def get_user_by_uuid(uuid_val: str) -> Optional[Dict[str, Any]]:
    return await get_db().get_user_by_uuid(uuid_val)

async def set_low_balance_notified(user_id: int, value: bool) -> None:
    await get_db().set_low_balance_notified(user_id, value)

async def get_user_balance(user_id: int) -> Optional[Decimal]:
    return await get_db().get_user_balance(user_id)

async def set_user_balance(user_id: int, amount_cents: int) -> bool:
    return await get_db().set_user_balance(user_id, amount_cents)

async def get_user_devices(user_id: int) -> List[Dict[str, Any]]:
    return await get_db().get_user_devices(user_id)

async def get_device_by_id(device_id: int) -> Optional[Dict[str, Any]]:
    return await get_db().get_device_by_id(device_id)

async def get_all_users_with_devices() -> List[int]:
    return await get_db().get_all_users_with_devices()

async def get_user_total_monthly_cost(user_id: int) -> Decimal:
    return await get_db().get_user_total_monthly_cost(user_id)

async def ensure_user_stub(user_id: int, username: str) -> None:
    await get_db().ensure_user_stub(user_id, username)


async def add_device(
    user_id: int,
    device_name: str,
    client_uuid: str,
    vless_link: str,
    monthly_cost_cents: int = 10000,
) -> int:
    return await get_db().add_device(
        user_id=user_id,
        device_name=device_name,
        client_uuid=client_uuid,
        vless_link=vless_link,
        monthly_cost_cents=monthly_cost_cents,
    )

async def deactivate_device(
    device_id: int,
    user_id: Optional[int] = None,
    reason: Optional[str] = None,
) -> bool:
    return await get_db().deactivate_device(device_id, user_id, reason)


async def activate_device(
    device_id: int,
    user_id: Optional[int] = None,
) -> bool:
    return await get_db().activate_device(device_id, user_id)

async def get_balance_transactions(
    user_id: int,
    limit: int = 50,
) -> List[Dict[str, Any]]:
    return await get_db().get_balance_transactions(user_id, limit)


async def get_payment_by_charge_ids(
    telegram_charge_id: str,
    provider_charge_id: str,
) -> Optional[Dict[str, Any]]:
    return await get_db().get_payment_by_charge_ids(
        telegram_charge_id,
        provider_charge_id,
    )

async def record_payment_idempotent(
    user_id: int,
    payload: str,
    telegram_charge_id: str,
    provider_charge_id: str,
    amount_cents: int,
) -> Dict[str, Any]:
    return await get_db().record_payment_idempotent(
        user_id=user_id,
        payload=payload,
        telegram_charge_id=telegram_charge_id,
        provider_charge_id=provider_charge_id,
        amount_cents=amount_cents,
    )

async def save_paid_access(
    user_id: int,
    username: str,
    vless_link: str,
    uuid_val: str,
) -> None:
    await get_db().save_paid_access(user_id, username, vless_link, uuid_val)

async def get_expired_trial_users() -> List[int]:
    return await get_db().get_expired_trial_users()

async def update_user_status(user_id: int, status: str) -> bool:
    return await get_db().update_user_status(user_id, status)
