"""Initial schema

Revision ID: 0001
Revises: -
Create Date: 2026-05-25

Создаёт таблицы и индексы в точности как schema.py.
Применяется один раз на чистой БД.
Если БД уже существует — помечаем текущую ревизию руками:
    alembic stamp 0001
"""
from __future__ import annotations

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # users
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS users (
            user_id               BIGINT PRIMARY KEY,
            username              TEXT,
            expire_at             TIMESTAMPTZ,
            vless_link            TEXT,
            uuid                  TEXT UNIQUE,
            status                TEXT NOT NULL DEFAULT 'NEW'
                                      CHECK (status IN ('NEW','TRIAL','ACTIVE','INACTIVE','EXPIRED')),
            notified              BOOLEAN NOT NULL DEFAULT FALSE,
            balance               BIGINT  NOT NULL DEFAULT 0 CHECK (balance >= 0),
            last_billing_date     DATE,
            low_balance_notified  BOOLEAN NOT NULL DEFAULT FALSE
        )
    """)

    # ------------------------------------------------------------------
    # devices
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS devices (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id         BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            device_name     TEXT    NOT NULL,
            client_uuid     TEXT    NOT NULL UNIQUE,
            vless_link      TEXT,
            monthly_cost    INTEGER NOT NULL DEFAULT 10000 CHECK (monthly_cost >= 0),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            is_active       BOOLEAN NOT NULL DEFAULT TRUE,
            disabled_at     TIMESTAMPTZ,
            disabled_reason TEXT
        )
    """)

    # ------------------------------------------------------------------
    # payments
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS payments (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id             BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            payload             TEXT    NOT NULL,
            telegram_charge_id  TEXT    NOT NULL,
            provider_charge_id  TEXT    NOT NULL,
            amount              INTEGER NOT NULL CHECK (amount >= 0),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            status              TEXT    NOT NULL DEFAULT 'PENDING',
            idempotency_key     TEXT
        )
    """)

    # ------------------------------------------------------------------
    # support_tickets
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS support_tickets (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id     BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            message     TEXT    NOT NULL
                            CHECK (char_length(message) >= 5 AND char_length(message) <= 1000),
            status      TEXT    NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending','answered','closed')),
            files       JSONB   NOT NULL DEFAULT '[]'::jsonb,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            answered_at TIMESTAMPTZ
        )
    """)

    # ------------------------------------------------------------------
    # balance_transactions
    # ------------------------------------------------------------------
    op.execute("""
        CREATE TABLE IF NOT EXISTS balance_transactions (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id          BIGINT  NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            kind             TEXT    NOT NULL
                                 CHECK (kind IN (
                                     'TOPUP',
                                     'DAILY_CHARGE',
                                     'ADMIN_ADJUSTMENT',
                                     'REFUND',
                                     'BONUS'
                                 )),
            amount_cents     BIGINT  NOT NULL CHECK (amount_cents >= 0),
            balance_before   BIGINT  NOT NULL CHECK (balance_before >= 0),
            balance_after    BIGINT  NOT NULL CHECK (balance_after >= 0),
            reference_type   TEXT,
            reference_id     TEXT,
            idempotency_key  TEXT,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)

    # ------------------------------------------------------------------
    # Индексы
    # ------------------------------------------------------------------
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_tg_charge_id
            ON payments(telegram_charge_id);

        CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_provider_charge_id
            ON payments(provider_charge_id);

        CREATE INDEX IF NOT EXISTS idx_payments_user_id
            ON payments(user_id);

        CREATE INDEX IF NOT EXISTS idx_devices_user_id
            ON devices(user_id);

        CREATE INDEX IF NOT EXISTS idx_devices_user_id_is_active
            ON devices(user_id, is_active);

        CREATE INDEX IF NOT EXISTS idx_users_uuid
            ON users(uuid);

        CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id
            ON support_tickets(user_id);

        CREATE INDEX IF NOT EXISTS idx_support_tickets_user_created
            ON support_tickets(user_id, created_at DESC);

        CREATE INDEX IF NOT EXISTS idx_balance_transactions_user_id
            ON balance_transactions(user_id);

        CREATE INDEX IF NOT EXISTS idx_balance_transactions_user_created_at
            ON balance_transactions(user_id, created_at DESC);

        CREATE UNIQUE INDEX IF NOT EXISTS idx_balance_transactions_idempotency_key
            ON balance_transactions(idempotency_key)
            WHERE idempotency_key IS NOT NULL;

        CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_idempotency_key
            ON payments(idempotency_key)
            WHERE idempotency_key IS NOT NULL;
    """)


def downgrade() -> None:
    # Порядок обратный — сначала зависимые таблицы
    op.execute("DROP TABLE IF EXISTS balance_transactions")
    op.execute("DROP TABLE IF EXISTS support_tickets")
    op.execute("DROP TABLE IF EXISTS payments")
    op.execute("DROP TABLE IF EXISTS devices")
    op.execute("DROP TABLE IF EXISTS users")
